### ISSUE TITLE
Add comments count

### ISSUE THREAD

**Issue by marcotroisi** [marcotroisi/blog#16]
I've added a comments count (https://github.com/marcotroisi/blog/pull/15), but it's not looking good.

How and where would be a good way to show the comments count in the article page? 

![screen shot 2017-02-08 at 17 38 39](https://cloud.githubusercontent.com/assets/429760/22749487/757e27d4-ee25-11e6-8791-383999d69319.png)

**Comment by marcotroisi** [comment]
@dimitraz @piccolazucca opinions are welcome 😄

**Comment by milenazuccarelli** [comment]
Hi marco, is that something you would ideally want at the top of the article page?  I reckon it would make more sense to put it at the bottom of the page, centered, just above the comments box. 
However, if it's information that you'd like to have on show, my first intuition would be to center it and place it just underneath the title - perhaps, in that case, it would make sense to pull the date down as well and have the two elements next to each other?

**Comment by marcotroisi** [comment]
I've noticed how many blogs have the comments count at the top of the article. Apparently, that helps with getting more people to leave their comment. A few links to give an idea:

- http://www.yegor256.com/2017/02/07/private-method-is-new-class.html
- https://michaelhyatt.com/dont-skip-lunch.html

I like your idea of having it centred on top, perhaps along with the date. I also love the way the date is at the moment. So I'm really not sure. 🤔
