### ISSUE TITLE
h1/h2 line height on blog posts

### ISSUE THREAD

**Issue by dimitraz** [marcotroisi/blog#19]
Too much line height when titles wrap on blog post pages. Could afford to go to 1.3 with a margin of .5em underneath, what do you think?

**Comment by marcotroisi** [comment]
100% agree. Just tried it with dev tools and it's much better the way you say.

**Comment by marcotroisi** [comment]
Done. https://github.com/marcotroisi/blog/commit/c9a93cdececc8e9d3370ec5edc9d32f68cbcec33
